name: $(BuildID)

trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run eslint
      npm run test
      npm run codecov -- --token=$(CODECOV_TOKEN)
      export COVERALLS_REPO_TOKEN=$(COVERALLS_TOKEN)
      export CI_BRANCH=$(Build.SourceBranch)
      export CI_BUILD_NUMBER=$(Build.BuildNumber)
      export CI_BUILD_URL=$(Build.BuildUri)
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    displayName: 'npm install and test'
