name: $(BuildID)

trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
      
  - script: |
      npm install
      npm run eslint
      npm run test
      npm run codecov -- --token=$(CODECOV_TOKEN)
      export APPVEYOR=true
      export APPVEYOR_BUILD_NUMBER=$(Build.BuildNumber)
      export APPVEYOR_BUILD_ID=$(Agent.OS)_$(node_version)
      export APPVEYOR_REPO_COMMIT=$(Build.SourceVersion)
      export APPVEYOR_REPO_BRANCH=$(Build.SourceBranchName)
      export COVERALLS_SERVICE_NAME=Azure Pipelines
      export COVERALLS_REPO_TOKEN=$(COVERALLS_TOKEN)
      export COVERALLS_PARALLEL=true
      export CI_PULL_REQUEST=$(System.PullRequest.PullRequestNumber)
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      
    displayName: 'npm install and test'
